// Generated by CoffeeScript 1.6.3
var SiteNavView,
  _this = this;

SiteNavView = Backbone.Marionette.ItemView.extend({
  template: JST["_attachments/templates/SiteNavView.handlebars"],
  events: {
    "click .navbar-nav li": "toggle"
  },
  toggle: function() {
    var toggle;
    console.log("Toggle");
    toggle = $(".navbar-toggle").is(":visible");
    if (toggle) {
      console.log("toggle");
      return $(".navbar-collapse").collapse('hide');
    }
  }
});
