// Generated by CoffeeScript 1.6.3
var StatsHeaderDashboardView, _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

StatsHeaderDashboardView = (function(_super) {
  __extends(StatsHeaderDashboardView, _super);

  function StatsHeaderDashboardView() {
    this.render = __bind(this.render, this);
    _ref = StatsHeaderDashboardView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  StatsHeaderDashboardView.prototype.tagName = 'p';

  StatsHeaderDashboardView.prototype.render = function() {
    return this.$el.html('<h2>' + polyglot.t("Statistics") + '<h2>');
  };

  return StatsHeaderDashboardView;

})(Backbone.View);
