// Generated by CoffeeScript 1.6.3
var Stat, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Stat = (function(_super) {
  __extends(Stat, _super);

  function Stat() {
    _ref = Stat.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Stat.prototype.initialize = function() {
    if (!this.attributes.createdAt) {
      this.set({
        collection: 'stat',
        createdAt: moment(new Date()).format(Coconut.config.get("datetime_format"))
      });
    }
    if (!this.attributes.lastModifiedAt) {
      return this.set({
        lastModifiedAt: moment(new Date()).format(Coconut.config.get("datetime_format"))
      });
    }
  };

  Stat.prototype.url = "/stat";

  return Stat;

})(Backbone.Model);
