// Generated by CoffeeScript 1.6.3
var StatsCollection, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

StatsCollection = (function(_super) {
  __extends(StatsCollection, _super);

  function StatsCollection() {
    _ref = StatsCollection.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  StatsCollection.prototype.model = Result;

  StatsCollection.prototype.url = '/result';

  StatsCollection.prototype.parse = function(response) {
    return response.rows;
  };

  return StatsCollection;

})(Backbone.Collection);
